version: '3.8'

services:
  company-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # 构建时的 API 基础路径（可选）
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-/api}
    image: company-analysis:latest
    container_name: company-analysis-app
    ports:
      - "${APP_PORT:-3000}:80"
    environment:
      # 运行时配置：后端 API 地址
      # 使用容器名或服务名访问后端（需要在同一网络）
      API_BACKEND_URL: ${API_BACKEND_URL:-http://backend:9080}
    restart: unless-stopped
    networks:
      - company-network

networks:
  company-network:
    driver: bridge